hw3 initial commit
ciaica-anastasia/ReactJS-Frontend-Web-Development pull request #1
Opened 2021-10-06 10:51 UTC by ciaica-anastasia

К сожалению, я забыла запушить базовую версию проекта. Мною были поменяны файлы App.js, Clock.jsx и App.css в сравнении с базовой версией.

2021-10-09 16:05 UTC, dshuran requested changes

2021-10-09 16:05 UTC, dshuran commented on my-app/src/App.js
> +      <Clock/>
Идея данного домашнего задания в том, чтобы использовать один компонент счётчика два раза. Вы же используете один компонент Clock. Непонятно, зачем он нужен, так можно и в рамках App весь код написать :)

2021-10-09 16:05 UTC, dshuran commented on my-app/src/Clock.jsx
> +            this.tickCount += 1;
Можно обойтись без лишней переменной tickCount, используя значение из state. Кроме того, у вас сейчас получился такой код, что если я захочу, чтобы второй счётчик считал не 10, а 15 раз, то у меня не получится это сделать. Это ещё один камень в сторону того, что необходим компонентный подход. Просьба поправить

2021-10-09 16:05 UTC, dshuran commented on my-app/src/Clock.jsx
> +        };
Первый счётчик должен считать от 0 до 10, второй от 10 до 20. У вас всё сдвинуто на 10 вверх.

2021-10-09 16:05 UTC, dshuran commented on my-app/src/Clock.jsx
> +            <div class="counter">
в JSX не используется слово class, т.к. оно является зарезервированным в JavaScript. Вместо него используйте className

2021-10-17 20:32 UTC, ciaica-anastasia commented on my-app/src/App.js
> +      <Clock/>
Исправлено

2021-10-17 20:32 UTC, ciaica-anastasia commented on my-app/src/Clock.jsx
> +            this.tickCount += 1;
Исправлено

2021-10-17 20:32 UTC, ciaica-anastasia commented on my-app/src/Clock.jsx
> +        };
Исправлено

2021-10-17 20:33 UTC, ciaica-anastasia commented on my-app/src/Clock.jsx
> +            <div class="counter">
Исправлено

2021-10-18 07:57 UTC, dshuran requested changes

2021-10-18 07:57 UTC, dshuran commented on my-app/src/Counter.jsx
> +            end: props.end
end же не изменяется, непонятно, зачем он в state.
а start можно было назвать как-нибудь по-другому, типа currentCount (текущее значение счётчика)

2021-10-18 07:57 UTC, dshuran commented on my-app/src/App.js
> +        <Counter name={"second"} start={10} end={20}/>
Форматирование поехало

2021-10-18 07:57 UTC, dshuran commented on my-app/src/Counter.jsx
> +                <h4>This is {this.state.name} counter!</h4>
Имя тоже можно не заносить в state, оно в данном случае не меняется же. И вообще оно приходит извне, т.е. это чистый проп, который нам передали. В state мы храним только то, что может изменяться при рендере или имеет отношение к этим изменениям. Но тут это чистая константа.

2021-10-23 18:19 UTC, ciaica-anastasia commented on my-app/src/Counter.jsx
> +            end: props.end
Поправила

2021-10-23 18:19 UTC, ciaica-anastasia commented on my-app/src/App.js
> +        <Counter name={"second"} start={10} end={20}/>
Поправила

2021-10-23 18:19 UTC, ciaica-anastasia commented on my-app/src/Counter.jsx
> +                <h4>This is {this.state.name} counter!</h4>
Поправила

2021-10-28 06:25 UTC, dshuran approved these changes

2021-10-28 06:25 UTC, merged